### ISSUE TITLE
Plugin interferes with default  login url

### ISSUE THREAD

**Issue by xuruicheng96** [dulabs/frontend-edit-profile#4]
When activated,  this plugin will overwrite the default login page,register page,lost password page , replacing it with a page that is listed first among all pages,  it seems to cause by the plugin setting in which you have to specify "Login URL or Page(drop-down list)", "Lost Password URL or (drop-down list)", and "Register URL or (drop-down list)", if leave blank ,it will use the first option from dropdown list which is the page that is listed first among all pages. 
So this issue will appear when the plugin is activated and settings is not specified
Please help to make the plugin not change any default website url when setting is not specified!
Thanks!

**Comment by dulabs** [comment]
I added option to override the url. See the patches.
