### ISSUE TITLE
Scripts and Styles are not enqueued using proper hooks

### ISSUE THREAD

**Issue by Moros1138** [dulabs/frontend-edit-profile#8]
When I was debugging I noticed that your plugin was including style and script even after I scrubbed the style and script hooks clean. Upon further investigation, I found you were using the hooks:

wp_print_styles and wp_print_scripts

to enqueue your styles and scripts respectively. In my implementation I switched those hooks for:

wp_enqueue_scripts

This allows developers to filter out the scripts and styles for situations where they aren't required! Mainly for speed of loading. The password strength meter is a BEAST by itself and it was being loaded on every single page!

You make a great plugin! Thank you for all of your hard work, I hope this helps to make it better!

**Comment by dulabs** [comment]
Thank you @Moros1138. If you had anything changes, you can do pull release.
